name: updata data scheduled

on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '30 7 * * *'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: '15.x'

    - name: Cache dependencies
      uses: actions/cache@v2
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-

    - run: npm ci
    - run: ./node_modules/kruk/bin/index.js --key $PSIKUS --file src/_urls/ecommerce.json --checkOrigin --output json > src/_data/crux-origin.json
      env:
        PSIKUS: ${{ secrets.PSIKUS }}
    - run: ./node_modules/kruk/bin/index.js --key $PSIKUS --file src/_urls/ecommerce.json --output json > src/_data/crux-home.json
      env:
        PSIKUS: ${{ secrets.PSIKUS }}
    - run: node createOrUpdateDataChart.mjs
    - run: npm run build
    - run: touch dist/.nojekyll
    - name: Get current date
      id: date
      run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
    - name: Commit & Push changes
      uses: actions-js/push@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        message: crux-data-${{ steps.date.outputs.date }}
        branch: 'master'

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./dist
        cname: crux.gotomi.info
